server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456ms
    url: jdbc:mysql://192.168.106.129:3306/20220327?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  redis:
    port: 6379
    host: 192.168.106.129

logging:
  level:
    com.lantu: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

